language: ruby

rvm:
  - 1.9.3

env:
  - PAGEFLOW_RAILS_VERSION=4.0.4
  - PAGEFLOW_RAILS_VERSION=4.1.6

services:
  - redis-server

script:
  - "xvfb-run bin/rspec"
  - "xvfb-run bin/teaspoon"

before_script:
    - mysql -e 'create database pageflow_dummy_test;'
