dist: trusty
language: ruby
rvm:
  - 2.3.1
  - 2.5.3

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false
cache:
  bundler: true
  directories:
    - node_modules

env:
  - PUBLISH_THEME_DOC=true COVERALLS_PARALLEL=true

services:
  - redis-server

before_install:
  - nvm install stable

before_script:
  - bin/npm install
  - bin/npm run build
  - bin/rake pageflow:dummy
  - bin/rake app:assets:precompile

script:
  - bin/rspec
  - bin/teaspoon
  - bin/npm test

after_success:
  - bundle exec publish-pageflow-theme-doc

notifications:
  webhooks: https://coveralls.io/webhook?service_name=travis-ci

addons:
  chrome: stable
