dist: xenial
language: ruby
rvm:
  - 2.3.1
  - 2.5.3

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false
cache:
  bundler: true
  directories:
    - node_modules

env:
  - PUBLISH_THEME_DOC=true COVERALLS_PARALLEL=true

services:
  - redis-server
  - mysql

before_install:
  - nvm install v10.17.0
  - gem update bundler

before_script:
  - yarn install
  - bin/build-packages

  - bin/rake pageflow:dummy
  - bin/rake app:assets:precompile

  # Precompile triggers `yarn install --production` which strips away
  # dev dependencies like Jest which are required below
  - yarn install

script:
  - bin/rspec
  - (cd packages/pageflow; yarn test)
  - (cd packages/pageflow-react; yarn test)
  - bin/teaspoon

after_success:
  - bundle exec publish-pageflow-theme-doc

notifications:
  webhooks: https://coveralls.io/webhook?service_name=travis-ci

addons:
  chrome: stable
